# Generated by Django 3.2 on 2024-11-07 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtistaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('distribuidora', models.CharField(max_length=50)),
                ('duracion', models.IntegerField()),
                ('num_reproducciones', models.IntegerField()),
                ('fecha_lanzamiento', models.DateField()),
                ('nombre_artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtistaApp.artista')),
            ],
        ),
    ]
