# Generated by Django 3.2 on 2024-11-07 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtistaApp', '0002_musica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_album', models.CharField(max_length=100)),
                ('fecha_lanzamiento', models.DateField()),
                ('genero_album', models.CharField(max_length=50)),
                ('discografica', models.CharField(max_length=100)),
                ('numero_de_canciones', models.IntegerField()),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumes', to='ArtistaApp.musica')),
            ],
        ),
    ]
