# Generated by Django 5.1.4 on 2024-12-16 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_artista', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('fechanacimiento', models.DateField()),
                ('cancionescreada', models.IntegerField()),
                ('aniosactivo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('distribuidora', models.CharField(max_length=50)),
                ('duracion', models.IntegerField()),
                ('num_reproducciones', models.IntegerField()),
                ('fecha_lanzamiento', models.DateField()),
                ('nombre_artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtistaAPI.artista')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_album', models.CharField(max_length=100)),
                ('fecha_lanzamiento', models.DateField()),
                ('genero_album', models.CharField(max_length=50)),
                ('discografica', models.CharField(max_length=100)),
                ('numero_de_canciones', models.IntegerField()),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumes', to='ArtistaAPI.musica')),
            ],
        ),
    ]
